# mi_lista = ["a", "b", "c", "d", "e", "f", "g", "h", "i"]

# print("**********************************************************************")
# print(mi_lista)
# print(mi_lista[0])
# print(mi_lista[1])
# print("**********************************************************************")
# print(mi_lista[-1])
# print(mi_lista[-2])
# print("**********************************************************************")
# print(mi_lista[0:2])
# print(mi_lista[0:3])
# print("**********************************************************************")
# print(mi_lista[0:7:2])
# print(mi_lista[0:7:3])
# print("**********************************************************************")
# print(f"El primer elemento de mi lista es {mi_lista[0]}")
# print("**********************************************************************")
# print(mi_lista[-2:])
# print(mi_lista[-4:])
# print("........................................................................")
# mi_lista[0] = "Julio Bocca"
# print(mi_lista)
# print("**********************************************************************")
# mi_lista[1:3] = ["segundo", "tercero"]
# print(mi_lista)
# print("........................................................................")
# mi_lista[:3] = []
# print(mi_lista)
# print("........................................................................")
# mi_lista = []
# print(mi_lista)
# mi_lista = ["a", "b", "c", "d", "e", "f", "g", "h", "i"]

# print("--------------------------------------------------")
# print(mi_lista)
# print(len(mi_lista))
# print("--------------------------------------------------")
# mi_lista.append("ELEMENTO QUE QUIERO AGREGAR")
# print(mi_lista)
# print("--------------------------------------------------")
# mi_lista.pop()
# print(mi_lista)
# print("--------------------------------------------------")
# mi_lista.pop(7)
# print(mi_lista)
# print("--------------------------------------------------")
# mi_lista.append("*")
# print(mi_lista)
# print("--------------------------------------------------")
# mi_lista.append("*" * 9)
# print(mi_lista)
# print("--------------------------------------------------")
# mi_lista = ["a", "b", "c", "d", "e", "f", "g", "h", "i"]
# print(mi_lista)
# print("--------------------------------------------------")
# print(
#     mi_lista.count("b")
#     )
# print("-----------------------")
# mi_lista.append("b")
# print(
#     mi_lista.count("b")
#     )
# print("-----------------------")
# mi_lista.append("b")
# mi_lista.append("b")
# mi_lista.append("b")
# mi_lista.append("b")
# mi_lista.append("b")
# print(mi_lista.count("b"))
# print("-----------------------")
# print(mi_lista.count("B"))
print("--------------------------------------------------")
mi_lista = ["a", "b", "c", "d", "i", "e", "f", "g", "h", "i"]
print(mi_lista)
print("--------------------------------------------------")
print(
    mi_lista.index("a")
    )
print("--------------------------------------------------")
print(
    mi_lista.index("i")
    )
# print("--------------------------------------------------")
# print(
#     mi_lista.index("El tesoro de One Piece")
#     )

